id: P4318F53A
initial_creation_type: input
source_metadata:
  title: Longevity Series
  language: fr
  description: 'Texts on the theme of longevity, including ritual practices to accomplish
    long life (tshe sgrub):'
  volume:
    5a6086617b5741f28d7b6b698a1fdec9:
      title: The Dhāraṇī of Amitāyus
      parent: Canonical Texts
    d72bd3f71c9a487d927b44bb10ec04cd:
      title: The Sūtra of Boundless Life and Wisdom
      parent: Canonical Texts
    5b356171478d4fb69c3e762a1d3328ea:
      title: 'A Shortcut to the Siddhi of Immortality: Guru Yoga of Union with the
        Three Deities of Long Life'
      parent: Guru Yoga
    4c763d5ea421482aaaed26f8e7b3eaea:
      title: 'The New Glorious Bestower of Immortality: A Long-Life Practice and Empowerment
        that Unites the Oral, Treasure and Visionary Teachings'
      parent: Practices
    f6598e518c1c4ee4b6ed64327bbdb602:
      title: The Sādhana and Empowerment for the Extremely Close Lineage of the Long-Life
        Practice that Unites the Oral, Treasure and Visionary Teachings
      parent: Practices
    0e9c55c0cb04469dbc919ad273e7fd25:
      title: 'Words of Advice on Accomplishing Immortality: An Extremely Concise Daily
        Practice Uniting the Short Lineages of Amitāyus and Hayagrīva'
      parent: Practices
    3180517f22d644b794cc256ae0fe2c36:
      title: 'The Vase of Immortal Life: The Long-Life Practice of the Vidyādharas,
        from the Heart Essence of the Vast Expanse'
      parent: Practices
    ddb04f345c8341438571e58ba0f5ef30:
      title: Extemporary Practice of Longevity for Oneself or Others
      parent: Practices
    2d7f790301a14b6c995627990221a292:
      title: How to Recite the Dhāraṇīsūtra of Amitāyus
      parent: Recitation Guides
    0d8803313d15440ba8e91b8fce6bf926:
      title: A Daily Long-Life Practice of Amitāyus
      parent: Sādhanas
    a7250f157cdf4493b4350762085125c2:
      title: 'The Sublime Path to Immortality: The Quintessence of Profoundly Secret
        Pith Instructions on Attaining Vajra Longevity'
      parent: Sādhanas
created_at: '2022-03-01T04:28:01.286279'
last_modified_at: '2022-03-01T04:28:01.286282'
